-- Innitial script to create table and initial data
DROP TABLE cities;
CREATE TABLE cities (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	city VARCHAR(128) NOT NULL, 
	state VARCHAR(128) NOT NULL
);

-- Initial data to table 
INSERT INTO cities(city, state) VALUES('Santiago de Querétaro', 'Querétaro');
INSERT INTO cities(city, state) VALUES('San Juan del Río', 'Querétaro');
INSERT INTO cities(city, state) VALUES('Tequisquiapan', 'Querétaro');
INSERT INTO cities(city, state) VALUES('Guadalajara', 'Jalisco');
INSERT INTO cities(city, state) VALUES('Huichapan', 'Hidalgo');
INSERT INTO cities(city, state) VALUES('Pachuca', 'Hidalgo');
INSERT INTO cities(city, state) VALUES('Actopan', 'Hidalgo');
INSERT INTO cities(city, state) VALUES('Mérida', 'Yucatán');
INSERT INTO cities(city, state) VALUES('Acapulco', 'Guerrero');
INSERT INTO cities(city, state) VALUES('Mazatlán', 'Sinaloa');
INSERT INTO cities(city, state) VALUES('Puebla de Zaragoza', 'Puebla');
INSERT INTO cities(city, state) VALUES('Cholula', 'Puebla');
INSERT INTO cities(city, state) VALUES('Zacatlán', 'Puebla');
INSERT INTO cities(city, state) VALUES('Xalapa', 'Veracruz');
INSERT INTO cities(city, state) VALUES('Morelia', 'Michoacán');

/*
 * Users table to manage access to API
 * Default user:
 * 	      username: quiron
 * 	  password_raw: esteganografia_01+
 * password_bcrypt: $2a$10$b1p96SYC4NAr6uUBVgCXSu9v6qFX0Qc/aPSKD03pLNGT/hoN7KtUu
 */
DROP TABLE users;
CREATE TABLE users (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	fullname VARCHAR(128) NOT NULL,
	email varchar(256) NOT NULL,
	username varchar(128) NOT NULL,
	passwd varchar(512) NOT NULL,
	is_active NUMBER(1) DEFAULT 0 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users(fullname, email, username, passwd, is_Active) VALUES
	('Alejandro Bravo', 'bravotorres.alejandro@gmail.com', 'quiron', '$2a$10$b1p96SYC4NAr6uUBVgCXSu9v6qFX0Qc/aPSKD03pLNGT/hoN7KtUu', 1);


-- SELECT * FROM cities;
-- SELECT * FROM users;
 